### PR TITLE
Attempting to block ads on ZEE5 media streaming platform

### PR DESCRIPTION
**Pull request by anudeepND**
ZEE5 is a video on demand website run by Zee Entertainment Enterprises Limited. It offers both free and paid content, free subscription has ads in the beginning which is not blocked. Also few trackers are also not blocked. This PR will try to eliminate all the ads and trackers both in app and in website.
Feel free to comment and contribute :)

### CODE REVIEW

**Comment by anudeepND** [comment]
`imasdk.googleapis.com`  seems to interfere with streaming not only in ZEE5 but also some other platforms. This domain was removed in https://github.com/anudeepND/blacklist/commit/c3c131b5f580c09d4ecb50f24e255680dd0f421f

**Comment by dnmTX** [comment]
zee5


:neutral_face:

**Comment by dnmTX** [comment]
https://github.com/lightswitch05/hosts/issues/29#issuecomment-432783866

**Comment by anudeepND** [comment]
@dnmTX I think they are only available in India, they are pretty popular here

**Comment by anudeepND** [comment]
> [lightswitch05/hosts#29 (comment)](https://github.com/lightswitch05/hosts/issues/29#issuecomment-432783866)

Oops I was forgotten, thanks for the link

**Comment by anudeepND** [comment]
Everything looks good. I have tested both app and website for a day with these domains blocked. No ads were displayed, no other shady domain was found. Merging...

**Pull request merged**
