### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by kaliangel**
Add domains file for Facebook

### CODE REVIEW

**Comment by kaliangel** [comment]
This file format can be useful.

**Comment by anudeepND** [comment]
There's already a [facebook blocklist](https://github.com/anudeepND/blacklist/blob/master/facebook.txt). The target IP address should be 0.0.0.0 and the list shouldn't contain any whatsapp or instagram domains.

**Comment by kaliangel** [comment]
@anudeepND this file is your blocklist but in a more useful format. A file with 0.0.0.0 as target doesn't block IPv6 requests.

**Comment by iot-Noob** [comment]
ok @kaliangel

**Comment by iot-Noob** [comment]
@kaliangel 
Do you want for browser or Facebook app ??

**Review by lastthyme — APPROVED** [review]

**Comment by anudeepND** [comment]
Closing due to inactivity

**Pull request closed without merging**
